version: "3.8"

services:
  app:
    build:
      context: ./node-api
      dockerfile: Dockerfile # Dockerfile do Node.js
    ports:
      - "5050:5050"
    volumes:
      - ./node-api:/usr/src/app
      - /usr/src/app/node_modules
      - ./node-api/database.sqlite:/usr/src/app/database/database.db
    environment:
      DATABASE_URL: "/usr/src/app/database/database.db"
      PORT: 5050

