version: "3.8"

services:
  app:
    build:
      context: ./node-api
      dockerfile: Dockerfile # Dockerfile do Node.js
    ports:
      - "3000:3000"
    volumes:
      - ./node-api:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - sqlite
    environment:
      DATABASE_URL: "sqlite:/usr/src/app/database/database.db"
    networks:
      - app-network

  sqlite:
    build:
      context: ./db
      dockerfile: Dockerfile # Dockerfile do SQLite
    volumes:
      - ./db/volume:/usr/src/app/database
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
